"use client"

import React from "react";
import { TikTokDisclosureOptions } from "@/components/modals/TikTokDisclosureOptions";
import type { AutomationWizardData } from "../AutomationWizard";

interface Step5TikTokDisclosureProps {
  data: AutomationWizardData;
  onChange: (data: AutomationWizardData) => void;
}

export function AutomationWizardStep5TikTokDisclosure({
  data,
  onChange,
}: Step5TikTokDisclosureProps) {
  const hasTikTok = data.platforms.includes("tiktok");

  return (
    <div className="space-y-6">
      {!hasTikTok && (
        <div className="rounded-lg bg-amber-500/10 border border-amber-500/20 p-4">
          <h3 className="font-semibold text-amber-600 mb-2">TikTok Not Selected</h3>
          <p className="text-sm text-amber-600/80">
            These settings only apply if TikTok is selected in the previous step. You can still configure them here for future use.
          </p>
        </div>
      )}

      <div>
        <h3 className="text-lg font-semibold mb-2">TikTok Disclosure Settings</h3>
        <p className="text-sm text-muted-foreground mb-6">
          Configure content disclosure and engagement settings that will apply to all posts generated by this automation on TikTok.
        </p>

        <TikTokDisclosureOptions
          settings={data.tiktokDisclosure}
          onChange={(newSettings) => {
            onChange({
              ...data,
              tiktokDisclosure: newSettings,
            });
          }}
        />
      </div>
    </div>
  );
}
