# Bridge for Post Supabase utilities - Re-exports from new feature location
from app.features.posts.supabase_db import (
    get_post,
    get_post_by_external_id,
    get_posts,
    get_posts_by_status,
    get_posts_by_template,
    get_scheduled_posts,
    get_posts_by_variant_set,
    create_post,
    update_post,
    update_post_status,
    update_post_storage_urls,
    update_post_content,
    update_post_metadata,
    delete_post,
    get_post_content,
    get_storage_urls,
    get_post_metadata,
    get_slide_count,
    is_post_published,
)

__all__ = [
    "get_post",
    "get_post_by_external_id",
    "get_posts",
    "get_posts_by_status",
    "get_posts_by_template",
    "get_scheduled_posts",
    "get_posts_by_variant_set",
    "create_post",
    "update_post",
    "update_post_status",
    "update_post_storage_urls",
    "update_post_content",
    "update_post_metadata",
    "delete_post",
    "get_post_content",
    "get_storage_urls",
    "get_post_metadata",
    "get_slide_count",
    "is_post_published",
]
