import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import { expect, userEvent, within } from "storybook/test";

import { Page } from "./Page";
import { SlideCarouselEditor } from "@/components/generation/SlideCarouselEditor";

const meta = {
  title: "Carousel Editor",
  component: SlideCarouselEditor,
  parameters: {
    // More on how to position stories at: https://storybook.js.org/docs/configure/story-layout
    layout: "fullscreen",
  },
} satisfies Meta<typeof Page>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Main: Story = {
  args: {
    post: {
      id: "9d55e622-65b2-4de0-b1c0-301a85fb6f26",
      content: {
        layout: {
          width: 1080,
          height: 1350,
          aspect_ratio: "4:5",
        },
        slides: [
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 600,
                id: "hook-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "MYTH: Eye contact builds trust. It actually kills your connection.",
                font_size: 48,
                font_style: "bold",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "hook",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0119_as_m.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 1,
          },
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 400,
                id: "header-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content: "The Social Lie",
                font_size: 55,
                font_style: "bold",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
              {
                x: 100,
                y: 700,
                id: "body-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "Movies teach us to stare. We think it shows confidence.",
                font_size: 48,
                font_style: "normal",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "header_and_body",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0130_as_m.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 2,
          },
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 400,
                id: "header-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content: "The Brain Truth",
                font_size: 55,
                font_style: "bold",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
              {
                x: 100,
                y: 700,
                id: "body-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "Constant staring triggers fight or flight. It creates subconscious tension.",
                font_size: 48,
                font_style: "normal",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "header_and_body",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0128_ss_n.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 3,
          },
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 400,
                id: "header-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content: "The Fix",
                font_size: 55,
                font_style: "bold",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
              {
                x: 100,
                y: 700,
                id: "body-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "Break gaze every 5 seconds. Look away to let them breathe.",
                font_size: 48,
                font_style: "normal",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "header_and_body",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0105_ps_f.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 4,
          },
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 400,
                id: "header-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content: "The Trap",
                font_size: 55,
                font_style: "bold",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
              {
                x: 100,
                y: 700,
                id: "body-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "I used to overdo this. We mistake intensity for intimacy.",
                font_size: 48,
                font_style: "normal",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "header_and_body",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0035_ps_m.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 5,
          },
          {
            dynamic: true,
            elements: [
              {
                x: 100,
                y: 700,
                id: "body-text",
                type: "text",
                align: "center",
                color: "#ffffff",
                width: 880,
                stroke: "#000000",
                content:
                  "At 1,000 followers, I'm releasing the 'Communication Vault' (100+ Scripts & Protocols) for free via the link in bio.\n\nFollow to join the waitlist.",
                font_size: 48,
                font_style: "normal",
                font_family: "Tiktok Sans",
                line_height: 1.3,
                shadow_blur: 6,
                shadow_color: "#000000",
                stroke_width: 4,
                letter_spacing: null,
                shadow_opacity: 0.5,
                shadow_offset_x: 0,
                shadow_offset_y: 2,
              },
            ],
            design_id: "body",
            background: {
              type: "image",
              color: null,
              image_url:
                "https://stock-read-worker.useradius.workers.dev/file?key=lifestyle_revamped/0121_as_m.avif",
              gradient_angle: null,
              gradient_colors: null,
            },
            image_prompt: null,
            slide_number: 6,
          },
        ],
        caption:
          "Stop staring at people. Use the 5 second rule to build real trust.",
        hashtags: [
          "#psychology",
          "#communication",
          "#socialskills",
          "#bodylanguage",
          "#neuroscience",
        ],
      },
      metadata: {},
      template_id: "1310741f-2fa4-4004-a564-e4e5582a50f9",
      brand_id: "51cc61f9-5958-4c41-8e7e-245192d431fa",
      variant_set_id: null,
      platform: "tiktok",
      storage_urls: {
        slides: [
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-0.avif",
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-1.avif",
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-2.avif",
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-3.avif",
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-4.avif",
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/slide-5.avif",
        ],
        thumbnail:
          "https://klwznwkionqlkxrqakke.supabase.co/storage/v1/object/public/slides/51cc61f9-5958-4c41-8e7e-245192d431fa/9d55e622-65b2-4de0-b1c0-301a85fb6f26/thumbnail.avif",
      },
      created_at: "2026-04-22T10:58:53.07454+00:00",
      updated_at: "2026-04-22T15:59:02.173473+00:00",
      scheduled_time: null,
      published_time: null,
      platform_ids: null,
      external_post_id: null,
      external_permalink: null,
      error_message: null,
      analytics_last_sync: null,
      generation_prompt: null,
      status: "draft",
      platform_captions: null,
      automation_id: null,
    },
  },
};
