

import random


stock_pack_manifest = {
  "clean_girl_lifestyle": {
    "ac_f": [
      "clean_girl_lifestyle/0001_ac_f.webp",
      "clean_girl_lifestyle/0002_ac_f.webp",
      "clean_girl_lifestyle/0003_ac_f.webp",
      "clean_girl_lifestyle/0004_ac_f.webp",
      "clean_girl_lifestyle/0005_ac_f.webp",
      "clean_girl_lifestyle/0006_ac_f.webp",
      "clean_girl_lifestyle/0007_ac_f.webp",
      "clean_girl_lifestyle/0008_ac_f.webp",
      "clean_girl_lifestyle/0009_ac_f.webp",
      "clean_girl_lifestyle/0011_ac_f.webp",
      "clean_girl_lifestyle/0013_ac_f.webp",
      "clean_girl_lifestyle/0014_ac_f.webp",
      "clean_girl_lifestyle/0015_ac_f.webp",
      "clean_girl_lifestyle/0017_ac_f.webp",
      "clean_girl_lifestyle/0018_ac_f.webp"
    ],
    "ac_m": [
      "clean_girl_lifestyle/0010_ac_m.webp",
      "clean_girl_lifestyle/0012_ac_m.webp",
      "clean_girl_lifestyle/0016_ac_m.webp"
    ],
    "as_f": [
      "clean_girl_lifestyle/0019_as_f.webp",
      "clean_girl_lifestyle/0020_as_f.webp",
      "clean_girl_lifestyle/0022_as_f.webp",
      "clean_girl_lifestyle/0023_as_f.webp",
      "clean_girl_lifestyle/0025_as_f.webp",
      "clean_girl_lifestyle/0026_as_f.webp",
      "clean_girl_lifestyle/0028_as_f.webp",
      "clean_girl_lifestyle/0029_as_f.webp",
      "clean_girl_lifestyle/0031_as_f.webp",
      "clean_girl_lifestyle/0032_as_f.webp",
      "clean_girl_lifestyle/0034_as_f.webp",
      "clean_girl_lifestyle/0035_as_f.webp",
      "clean_girl_lifestyle/0037_as_f.webp",
      "clean_girl_lifestyle/0038_as_f.webp",
      "clean_girl_lifestyle/0040_as_f.webp",
      "clean_girl_lifestyle/0041_as_f.webp",
      "clean_girl_lifestyle/0043_as_f.webp",
      "clean_girl_lifestyle/0044_as_f.webp",
      "clean_girl_lifestyle/0046_as_f.webp",
      "clean_girl_lifestyle/0047_as_f.webp"
    ],
    "as_m": [
      "clean_girl_lifestyle/0021_as_m.webp",
      "clean_girl_lifestyle/0024_as_m.webp",
      "clean_girl_lifestyle/0027_as_m.webp",
      "clean_girl_lifestyle/0030_as_m.webp",
      "clean_girl_lifestyle/0033_as_m.webp",
      "clean_girl_lifestyle/0036_as_m.webp",
      "clean_girl_lifestyle/0039_as_m.webp",
      "clean_girl_lifestyle/0042_as_m.webp",
      "clean_girl_lifestyle/0045_as_m.webp",
      "clean_girl_lifestyle/0048_as_m.webp"
    ],
    "ps_f": [
      "clean_girl_lifestyle/0049_ps_f.webp",
      "clean_girl_lifestyle/0050_ps_f.webp",
      "clean_girl_lifestyle/0052_ps_f.webp",
      "clean_girl_lifestyle/0053_ps_f.webp",
      "clean_girl_lifestyle/0055_ps_f.webp",
      "clean_girl_lifestyle/0056_ps_f.webp",
      "clean_girl_lifestyle/0058_ps_f.webp",
      "clean_girl_lifestyle/0059_ps_f.webp",
      "clean_girl_lifestyle/0061_ps_f.webp",
      "clean_girl_lifestyle/0062_ps_f.webp",
      "clean_girl_lifestyle/0064_ps_f.webp",
      "clean_girl_lifestyle/0065_ps_f.webp",
      "clean_girl_lifestyle/0067_ps_f.webp",
      "clean_girl_lifestyle/0069_ps_f.webp",
      "clean_girl_lifestyle/0070_ps_f.webp",
      "clean_girl_lifestyle/0072_ps_f.webp"
    ],
    "ps_m": [
      "clean_girl_lifestyle/0051_ps_m.webp",
      "clean_girl_lifestyle/0054_ps_m.webp",
      "clean_girl_lifestyle/0057_ps_m.webp",
      "clean_girl_lifestyle/0060_ps_m.webp",
      "clean_girl_lifestyle/0063_ps_m.webp",
      "clean_girl_lifestyle/0066_ps_m.webp",
      "clean_girl_lifestyle/0068_ps_m.webp",
      "clean_girl_lifestyle/0071_ps_m.webp"
    ],
    "ss_n": [
      "clean_girl_lifestyle/0073_ss_n.webp",
      "clean_girl_lifestyle/0074_ss_n.webp",
      "clean_girl_lifestyle/0075_ss_n.webp",
      "clean_girl_lifestyle/0076_ss_n.webp",
      "clean_girl_lifestyle/0077_ss_n.webp",
      "clean_girl_lifestyle/0078_ss_n.webp",
      "clean_girl_lifestyle/0079_ss_n.webp",
      "clean_girl_lifestyle/0080_ss_n.webp",
      "clean_girl_lifestyle/0081_ss_n.webp",
      "clean_girl_lifestyle/0082_ss_n.webp",
      "clean_girl_lifestyle/0083_ss_n.webp",
      "clean_girl_lifestyle/0084_ss_n.webp",
      "clean_girl_lifestyle/0085_ss_n.webp",
      "clean_girl_lifestyle/0086_ss_n.webp",
      "clean_girl_lifestyle/0087_ss_n.webp",
      "clean_girl_lifestyle/0088_ss_n.webp",
      "clean_girl_lifestyle/0089_ss_n.webp",
      "clean_girl_lifestyle/0090_ss_n.webp",
      "clean_girl_lifestyle/0091_ss_n.webp",
      "clean_girl_lifestyle/0092_ss_n.webp",
      "clean_girl_lifestyle/0093_ss_n.webp",
      "clean_girl_lifestyle/0094_ss_n.webp",
      "clean_girl_lifestyle/0095_ss_n.webp",
      "clean_girl_lifestyle/0096_ss_n.webp",
      "clean_girl_lifestyle/0097_ss_n.webp",
      "clean_girl_lifestyle/0098_ss_n.webp",
      "clean_girl_lifestyle/0099_ss_n.webp",
      "clean_girl_lifestyle/0100_ss_n.webp",
      "clean_girl_lifestyle/0101_ss_n.webp",
      "clean_girl_lifestyle/0102_ss_n.webp",
      "clean_girl_lifestyle/0103_ss_n.webp",
      "clean_girl_lifestyle/0104_ss_n.webp",
      "clean_girl_lifestyle/0105_ss_n.webp",
      "clean_girl_lifestyle/0106_ss_n.webp",
      "clean_girl_lifestyle/0107_ss_n.webp",
      "clean_girl_lifestyle/0108_ss_n.webp",
      "clean_girl_lifestyle/0109_ss_n.webp",
      "clean_girl_lifestyle/0110_ss_n.webp",
      "clean_girl_lifestyle/0111_ss_n.webp",
      "clean_girl_lifestyle/0112_ss_n.webp",
      "clean_girl_lifestyle/0113_ss_n.webp",
      "clean_girl_lifestyle/0114_ss_n.webp",
      "clean_girl_lifestyle/0115_ss_n.webp",
      "clean_girl_lifestyle/0116_ss_n.webp",
      "clean_girl_lifestyle/0118_ss_n.webp",
      "clean_girl_lifestyle/0119_ss_n.webp",
      "clean_girl_lifestyle/0120_ss_n.webp"
    ]
  },
  "coquette_lifestyle": {
    "ac_f": [
      "coquette_lifestyle/0001_ac_f.webp",
      "coquette_lifestyle/0002_ac_f.webp",
      "coquette_lifestyle/0003_ac_f.webp",
      "coquette_lifestyle/0004_ac_f.webp",
      "coquette_lifestyle/0005_ac_f.webp",
      "coquette_lifestyle/0006_ac_f.webp",
      "coquette_lifestyle/0007_ac_f.webp",
      "coquette_lifestyle/0008_ac_f.webp",
      "coquette_lifestyle/0009_ac_f.webp",
      "coquette_lifestyle/0010_ac_f.webp",
      "coquette_lifestyle/0011_ac_f.webp",
      "coquette_lifestyle/0012_ac_f.webp",
      "coquette_lifestyle/0013_ac_f.webp",
      "coquette_lifestyle/0014_ac_f.webp"
    ],
    "as_f": [
      "coquette_lifestyle/0015_as_f.webp",
      "coquette_lifestyle/0016_as_f.webp",
      "coquette_lifestyle/0017_as_f.webp",
      "coquette_lifestyle/0018_as_f.webp",
      "coquette_lifestyle/0019_as_f.webp",
      "coquette_lifestyle/0020_as_f.webp",
      "coquette_lifestyle/0021_as_f.webp",
      "coquette_lifestyle/0022_as_f.webp",
      "coquette_lifestyle/0023_as_f.webp",
      "coquette_lifestyle/0024_as_f.webp",
      "coquette_lifestyle/0025_as_f.webp",
      "coquette_lifestyle/0026_as_f.webp",
      "coquette_lifestyle/0027_as_f.webp",
      "coquette_lifestyle/0028_as_f.webp",
      "coquette_lifestyle/0029_as_f.webp",
      "coquette_lifestyle/0030_as_f.webp",
      "coquette_lifestyle/0031_as_f.webp",
      "coquette_lifestyle/0032_as_f.webp",
      "coquette_lifestyle/0033_as_f.webp",
      "coquette_lifestyle/0034_as_f.webp",
      "coquette_lifestyle/0035_as_f.webp",
      "coquette_lifestyle/0036_as_f.webp",
      "coquette_lifestyle/0037_as_f.webp"
    ],
    "ps_f": [
      "coquette_lifestyle/0038_ps_f.webp",
      "coquette_lifestyle/0039_ps_f.webp",
      "coquette_lifestyle/0040_ps_f.webp",
      "coquette_lifestyle/0041_ps_f.webp",
      "coquette_lifestyle/0042_ps_f.webp",
      "coquette_lifestyle/0043_ps_f.webp",
      "coquette_lifestyle/0044_ps_f.webp",
      "coquette_lifestyle/0045_ps_f.webp",
      "coquette_lifestyle/0046_ps_f.webp",
      "coquette_lifestyle/0047_ps_f.webp",
      "coquette_lifestyle/0048_ps_f.webp",
      "coquette_lifestyle/0049_ps_f.webp",
      "coquette_lifestyle/0050_ps_f.webp",
      "coquette_lifestyle/0051_ps_f.webp",
      "coquette_lifestyle/0052_ps_f.webp",
      "coquette_lifestyle/0053_ps_f.webp",
      "coquette_lifestyle/0054_ps_f.webp",
      "coquette_lifestyle/0055_ps_f.webp"
    ],
    "ss_n": [
      "coquette_lifestyle/0056_ss_n.webp",
      "coquette_lifestyle/0057_ss_n.webp",
      "coquette_lifestyle/0058_ss_n.webp",
      "coquette_lifestyle/0059_ss_n.webp",
      "coquette_lifestyle/0060_ss_n.webp",
      "coquette_lifestyle/0061_ss_n.webp",
      "coquette_lifestyle/0062_ss_n.webp",
      "coquette_lifestyle/0063_ss_n.webp",
      "coquette_lifestyle/0064_ss_n.webp",
      "coquette_lifestyle/0065_ss_n.webp",
      "coquette_lifestyle/0066_ss_n.webp",
      "coquette_lifestyle/0067_ss_n.webp",
      "coquette_lifestyle/0068_ss_n.webp",
      "coquette_lifestyle/0069_ss_n.webp",
      "coquette_lifestyle/0070_ss_n.webp",
      "coquette_lifestyle/0071_ss_n.webp",
      "coquette_lifestyle/0072_ss_n.webp",
      "coquette_lifestyle/0073_ss_n.webp",
      "coquette_lifestyle/0074_ss_n.webp",
      "coquette_lifestyle/0075_ss_n.webp",
      "coquette_lifestyle/0076_ss_n.webp",
      "coquette_lifestyle/0077_ss_n.webp",
      "coquette_lifestyle/0078_ss_n.webp",
      "coquette_lifestyle/0079_ss_n.webp",
      "coquette_lifestyle/0080_ss_n.webp",
      "coquette_lifestyle/0081_ss_n.webp",
      "coquette_lifestyle/0082_ss_n.webp",
      "coquette_lifestyle/0083_ss_n.webp",
      "coquette_lifestyle/0084_ss_n.webp",
      "coquette_lifestyle/0085_ss_n.webp",
      "coquette_lifestyle/0086_ss_n.webp",
      "coquette_lifestyle/0087_ss_n.webp",
      "coquette_lifestyle/0088_ss_n.webp",
      "coquette_lifestyle/0089_ss_n.webp",
      "coquette_lifestyle/0090_ss_n.webp"
    ]
  },
  "cottege-core-lifestyle": {
    "ac_f": [
      "cottege-core-lifestyle/0001_ac_f.webp",
      "cottege-core-lifestyle/0002_ac_f.webp",
      "cottege-core-lifestyle/0003_ac_f.webp",
      "cottege-core-lifestyle/0004_ac_f.webp",
      "cottege-core-lifestyle/0006_ac_f.webp",
      "cottege-core-lifestyle/0007_ac_f.webp",
      "cottege-core-lifestyle/0008_ac_f.webp",
      "cottege-core-lifestyle/0010_ac_f.webp",
      "cottege-core-lifestyle/0011_ac_f.webp",
      "cottege-core-lifestyle/0012_ac_f.webp",
      "cottege-core-lifestyle/0013_ac_f.webp",
      "cottege-core-lifestyle/0015_ac_f.webp",
      "cottege-core-lifestyle/0016_ac_f.webp",
      "cottege-core-lifestyle/0017_ac_f.webp",
      "cottege-core-lifestyle/0018_ac_f.webp"
    ],
    "ac_m": [
      "cottege-core-lifestyle/0005_ac_m.webp",
      "cottege-core-lifestyle/0009_ac_m.webp",
      "cottege-core-lifestyle/0014_ac_m.webp"
    ],
    "as_f": [
      "cottege-core-lifestyle/0019_as_f.webp",
      "cottege-core-lifestyle/0020_as_f.webp",
      "cottege-core-lifestyle/0022_as_f.webp",
      "cottege-core-lifestyle/0023_as_f.webp",
      "cottege-core-lifestyle/0025_as_f.webp",
      "cottege-core-lifestyle/0026_as_f.webp",
      "cottege-core-lifestyle/0027_as_f.webp",
      "cottege-core-lifestyle/0029_as_f.webp",
      "cottege-core-lifestyle/0030_as_f.webp",
      "cottege-core-lifestyle/0031_as_f.webp",
      "cottege-core-lifestyle/0032_as_f.webp",
      "cottege-core-lifestyle/0034_as_f.webp",
      "cottege-core-lifestyle/0035_as_f.webp",
      "cottege-core-lifestyle/0037_as_f.webp",
      "cottege-core-lifestyle/0038_as_f.webp",
      "cottege-core-lifestyle/0039_as_f.webp",
      "cottege-core-lifestyle/0041_as_f.webp",
      "cottege-core-lifestyle/0042_as_f.webp",
      "cottege-core-lifestyle/0043_as_f.webp",
      "cottege-core-lifestyle/0045_as_f.webp",
      "cottege-core-lifestyle/0046_as_f.webp",
      "cottege-core-lifestyle/0047_as_f.webp"
    ],
    "as_m": [
      "cottege-core-lifestyle/0021_as_m.webp",
      "cottege-core-lifestyle/0024_as_m.webp",
      "cottege-core-lifestyle/0028_as_m.webp",
      "cottege-core-lifestyle/0033_as_m.webp",
      "cottege-core-lifestyle/0036_as_m.webp",
      "cottege-core-lifestyle/0040_as_m.webp",
      "cottege-core-lifestyle/0044_as_m.webp",
      "cottege-core-lifestyle/0048_as_m.webp"
    ],
    "ps_f": [
      "cottege-core-lifestyle/0049_ps_f.webp",
      "cottege-core-lifestyle/0050_ps_f.webp",
      "cottege-core-lifestyle/0052_ps_f.webp",
      "cottege-core-lifestyle/0053_ps_f.webp",
      "cottege-core-lifestyle/0054_ps_f.webp",
      "cottege-core-lifestyle/0056_ps_f.webp",
      "cottege-core-lifestyle/0057_ps_f.webp",
      "cottege-core-lifestyle/0058_ps_f.webp",
      "cottege-core-lifestyle/0060_ps_f.webp",
      "cottege-core-lifestyle/0061_ps_f.webp",
      "cottege-core-lifestyle/0062_ps_f.webp",
      "cottege-core-lifestyle/0064_ps_f.webp",
      "cottege-core-lifestyle/0065_ps_f.webp",
      "cottege-core-lifestyle/0067_ps_f.webp",
      "cottege-core-lifestyle/0069_ps_f.webp",
      "cottege-core-lifestyle/0070_ps_f.webp",
      "cottege-core-lifestyle/0071_ps_f.webp",
      "cottege-core-lifestyle/0072_ps_f.webp"
    ],
    "ps_m": [
      "cottege-core-lifestyle/0051_ps_m.webp",
      "cottege-core-lifestyle/0055_ps_m.webp",
      "cottege-core-lifestyle/0059_ps_m.webp",
      "cottege-core-lifestyle/0063_ps_m.webp",
      "cottege-core-lifestyle/0068_ps_m.webp"
    ],
    "ss_n": [
      "cottege-core-lifestyle/0073_ss_n.webp",
      "cottege-core-lifestyle/0074_ss_n.webp",
      "cottege-core-lifestyle/0075_ss_n.webp",
      "cottege-core-lifestyle/0076_ss_n.webp",
      "cottege-core-lifestyle/0077_ss_n.webp",
      "cottege-core-lifestyle/0078_ss_n.webp",
      "cottege-core-lifestyle/0079_ss_n.webp",
      "cottege-core-lifestyle/0080_ss_n.webp",
      "cottege-core-lifestyle/0081_ss_n.webp",
      "cottege-core-lifestyle/0082_ss_n.webp",
      "cottege-core-lifestyle/0083_ss_n.webp",
      "cottege-core-lifestyle/0084_ss_n.webp",
      "cottege-core-lifestyle/0085_ss_n.webp",
      "cottege-core-lifestyle/0086_ss_n.webp",
      "cottege-core-lifestyle/0087_ss_n.webp",
      "cottege-core-lifestyle/0088_ss_n.webp",
      "cottege-core-lifestyle/0089_ss_n.webp",
      "cottege-core-lifestyle/0090_ss_n.webp",
      "cottege-core-lifestyle/0091_ss_n.webp",
      "cottege-core-lifestyle/0092_ss_n.webp",
      "cottege-core-lifestyle/0093_ss_n.webp",
      "cottege-core-lifestyle/0094_ss_n.webp",
      "cottege-core-lifestyle/0095_ss_n.webp",
      "cottege-core-lifestyle/0096_ss_n.webp",
      "cottege-core-lifestyle/0097_ss_n.webp",
      "cottege-core-lifestyle/0098_ss_n.webp",
      "cottege-core-lifestyle/0099_ss_n.webp",
      "cottege-core-lifestyle/0100_ss_n.webp",
      "cottege-core-lifestyle/0102_ss_n.webp",
      "cottege-core-lifestyle/0103_ss_n.webp",
      "cottege-core-lifestyle/0104_ss_n.webp",
      "cottege-core-lifestyle/0105_ss_n.webp",
      "cottege-core-lifestyle/0106_ss_n.webp",
      "cottege-core-lifestyle/0107_ss_n.webp",
      "cottege-core-lifestyle/0108_ss_n.webp",
      "cottege-core-lifestyle/0109_ss_n.webp",
      "cottege-core-lifestyle/0110_ss_n.webp",
      "cottege-core-lifestyle/0111_ss_n.webp",
      "cottege-core-lifestyle/0112_ss_n.webp",
      "cottege-core-lifestyle/0113_ss_n.webp",
      "cottege-core-lifestyle/0114_ss_n.webp",
      "cottege-core-lifestyle/0115_ss_n.webp",
      "cottege-core-lifestyle/0116_ss_n.webp",
      "cottege-core-lifestyle/0117_ss_n.webp",
      "cottege-core-lifestyle/0118_ss_n.webp",
      "cottege-core-lifestyle/0119_ss_n.webp",
      "cottege-core-lifestyle/0120_ss_n.webp"
    ]
  },
  "dark_luxury_lifestyle": {
    "ac_f": [
      "dark_lifestyle_ugc_v2/0001_ac_f.webp",
      "dark_lifestyle_ugc_v2/0002_ac_f.webp",
      "dark_lifestyle_ugc_v2/0004_ac_f.webp",
      "dark_lifestyle_ugc_v2/0006_ac_f.webp",
      "dark_lifestyle_ugc_v2/0008_ac_f.webp",
      "dark_lifestyle_ugc_v2/0009_ac_f.webp",
      "dark_lifestyle_ugc_v2/0011_ac_f.webp"
    ],
    "ac_m": [
      "dark_lifestyle_ugc_v2/0003_ac_m.webp",
      "dark_lifestyle_ugc_v2/0005_ac_m.webp",
      "dark_lifestyle_ugc_v2/0007_ac_m.webp",
      "dark_lifestyle_ugc_v2/0010_ac_m.webp",
      "dark_lifestyle_ugc_v2/0012_ac_m.webp"
    ],
    "as_f": [
      "dark_lifestyle_ugc_v2/0013_as_f.webp",
      "dark_lifestyle_ugc_v2/0015_as_f.webp",
      "dark_lifestyle_ugc_v2/0017_as_f.webp",
      "dark_lifestyle_ugc_v2/0019_as_f.webp",
      "dark_lifestyle_ugc_v2/0020_as_f.webp",
      "dark_lifestyle_ugc_v2/0022_as_f.webp",
      "dark_lifestyle_ugc_v2/0024_as_f.webp",
      "dark_lifestyle_ugc_v2/0025_as_f.webp",
      "dark_lifestyle_ugc_v2/0027_as_f.webp",
      "dark_lifestyle_ugc_v2/0029_as_f.webp",
      "dark_lifestyle_ugc_v2/0031_as_f.webp"
    ],
    "as_m": [
      "dark_lifestyle_ugc_v2/0014_as_m.webp",
      "dark_lifestyle_ugc_v2/0016_as_m.webp",
      "dark_lifestyle_ugc_v2/0018_as_m.webp",
      "dark_lifestyle_ugc_v2/0021_as_m.webp",
      "dark_lifestyle_ugc_v2/0023_as_m.webp",
      "dark_lifestyle_ugc_v2/0026_as_m.webp",
      "dark_lifestyle_ugc_v2/0028_as_m.webp",
      "dark_lifestyle_ugc_v2/0030_as_m.webp",
      "dark_lifestyle_ugc_v2/0032_as_m.webp"
    ],
    "ps_f": [
      "dark_lifestyle_ugc_v2/0033_ps_f.webp",
      "dark_lifestyle_ugc_v2/0035_ps_f.webp",
      "dark_lifestyle_ugc_v2/0037_ps_f.webp",
      "dark_lifestyle_ugc_v2/0039_ps_f.webp",
      "dark_lifestyle_ugc_v2/0040_ps_f.webp",
      "dark_lifestyle_ugc_v2/0042_ps_f.webp",
      "dark_lifestyle_ugc_v2/0044_ps_f.webp",
      "dark_lifestyle_ugc_v2/0046_ps_f.webp",
      "dark_lifestyle_ugc_v2/0048_ps_f.webp"
    ],
    "ps_m": [
      "dark_lifestyle_ugc_v2/0034_ps_m.webp",
      "dark_lifestyle_ugc_v2/0036_ps_m.webp",
      "dark_lifestyle_ugc_v2/0038_ps_m.webp",
      "dark_lifestyle_ugc_v2/0041_ps_m.webp",
      "dark_lifestyle_ugc_v2/0043_ps_m.webp",
      "dark_lifestyle_ugc_v2/0045_ps_m.webp",
      "dark_lifestyle_ugc_v2/0047_ps_m.webp"
    ],
    "ss_n": [
      "dark_lifestyle_ugc_v2/0049_ss_n.webp",
      "dark_lifestyle_ugc_v2/0050_ss_n.webp",
      "dark_lifestyle_ugc_v2/0051_ss_n.webp",
      "dark_lifestyle_ugc_v2/0052_ss_n.webp",
      "dark_lifestyle_ugc_v2/0053_ss_n.webp",
      "dark_lifestyle_ugc_v2/0054_ss_n.webp",
      "dark_lifestyle_ugc_v2/0055_ss_n.webp",
      "dark_lifestyle_ugc_v2/0056_ss_n.webp",
      "dark_lifestyle_ugc_v2/0057_ss_n.webp",
      "dark_lifestyle_ugc_v2/0058_ss_n.webp",
      "dark_lifestyle_ugc_v2/0059_ss_n.webp",
      "dark_lifestyle_ugc_v2/0060_ss_n.webp",
      "dark_lifestyle_ugc_v2/0061_ss_n.webp",
      "dark_lifestyle_ugc_v2/0062_ss_n.webp",
      "dark_lifestyle_ugc_v2/0064_ss_n.webp",
      "dark_lifestyle_ugc_v2/0065_ss_n.webp",
      "dark_lifestyle_ugc_v2/0066_ss_n.webp",
      "dark_lifestyle_ugc_v2/0067_ss_n.webp",
      "dark_lifestyle_ugc_v2/0068_ss_n.webp",
      "dark_lifestyle_ugc_v2/0069_ss_n.webp",
      "dark_lifestyle_ugc_v2/0070_ss_n.webp",
      "dark_lifestyle_ugc_v2/0071_ss_n.webp",
      "dark_lifestyle_ugc_v2/0072_ss_n.webp",
      "dark_lifestyle_ugc_v2/0073_ss_n.webp",
      "dark_lifestyle_ugc_v2/0074_ss_n.webp",
      "dark_lifestyle_ugc_v2/0075_ss_n.webp",
      "dark_lifestyle_ugc_v2/0076_ss_n.webp",
      "dark_lifestyle_ugc_v2/0077_ss_n.webp",
      "dark_lifestyle_ugc_v2/0078_ss_n.webp",
      "dark_lifestyle_ugc_v2/0079_ss_n.webp",
      "dark_lifestyle_ugc_v2/0080_ss_n.webp"
    ]
  },
  "miami_lifestyle": {
    "ac_f": [
      "miami_ugc/0001_ac_f.webp",
      "miami_ugc/0002_ac_f.webp",
      "miami_ugc/0004_ac_f.webp",
      "miami_ugc/0005_ac_f.webp",
      "miami_ugc/0007_ac_f.webp",
      "miami_ugc/0008_ac_f.webp",
      "miami_ugc/0010_ac_f.webp",
      "miami_ugc/0011_ac_f.webp",
      "miami_ugc/0013_ac_f.webp",
      "miami_ugc/0014_ac_f.webp",
      "miami_ugc/0016_ac_f.webp",
      "miami_ugc/0017_ac_f.webp"
    ],
    "ac_m": [
      "miami_ugc/0003_ac_m.webp",
      "miami_ugc/0006_ac_m.webp",
      "miami_ugc/0009_ac_m.webp",
      "miami_ugc/0012_ac_m.webp",
      "miami_ugc/0015_ac_m.webp",
      "miami_ugc/0018_ac_m.webp"
    ],
    "as_f": [
      "miami_ugc/0019_as_f.webp",
      "miami_ugc/0020_as_f.webp",
      "miami_ugc/0022_as_f.webp",
      "miami_ugc/0023_as_f.webp",
      "miami_ugc/0025_as_f.webp",
      "miami_ugc/0026_as_f.webp",
      "miami_ugc/0028_as_f.webp",
      "miami_ugc/0029_as_f.webp",
      "miami_ugc/0031_as_f.webp",
      "miami_ugc/0032_as_f.webp",
      "miami_ugc/0034_as_f.webp",
      "miami_ugc/0035_as_f.webp",
      "miami_ugc/0037_as_f.webp",
      "miami_ugc/0038_as_f.webp",
      "miami_ugc/0039_as_f.webp",
      "miami_ugc/0042_as_f.webp",
      "miami_ugc/0044_as_f.webp",
      "miami_ugc/0045_as_f.webp",
      "miami_ugc/0047_as_f.webp",
      "miami_ugc/0048_as_f.webp"
    ],
    "as_m": [
      "miami_ugc/0021_as_m.webp",
      "miami_ugc/0024_as_m.webp",
      "miami_ugc/0027_as_m.webp",
      "miami_ugc/0030_as_m.webp",
      "miami_ugc/0033_as_m.webp",
      "miami_ugc/0036_as_m.webp",
      "miami_ugc/0040_as_m.webp",
      "miami_ugc/0043_as_m.webp",
      "miami_ugc/0046_as_m.webp"
    ],
    "ps_f": [
      "miami_ugc/0049_ps_f.webp",
      "miami_ugc/0051_ps_f.webp",
      "miami_ugc/0052_ps_f.webp",
      "miami_ugc/0054_ps_f.webp",
      "miami_ugc/0055_ps_f.webp",
      "miami_ugc/0057_ps_f.webp",
      "miami_ugc/0058_ps_f.webp",
      "miami_ugc/0061_ps_f.webp",
      "miami_ugc/0063_ps_f.webp",
      "miami_ugc/0064_ps_f.webp",
      "miami_ugc/0066_ps_f.webp",
      "miami_ugc/0067_ps_f.webp",
      "miami_ugc/0069_ps_f.webp",
      "miami_ugc/0071_ps_f.webp",
      "miami_ugc/0072_ps_f.webp"
    ],
    "ps_m": [
      "miami_ugc/0050_ps_m.webp",
      "miami_ugc/0053_ps_m.webp",
      "miami_ugc/0056_ps_m.webp",
      "miami_ugc/0059_ps_m.webp",
      "miami_ugc/0062_ps_m.webp",
      "miami_ugc/0065_ps_m.webp",
      "miami_ugc/0068_ps_m.webp",
      "miami_ugc/0070_ps_m.webp"
    ],
    "ss_n": [
      "miami_ugc/0073_ss_n.webp",
      "miami_ugc/0074_ss_n.webp",
      "miami_ugc/0075_ss_n.webp",
      "miami_ugc/0076_ss_n.webp",
      "miami_ugc/0077_ss_n.webp",
      "miami_ugc/0078_ss_n.webp",
      "miami_ugc/0079_ss_n.webp",
      "miami_ugc/0080_ss_n.webp",
      "miami_ugc/0081_ss_n.webp",
      "miami_ugc/0082_ss_n.webp",
      "miami_ugc/0083_ss_n.webp",
      "miami_ugc/0084_ss_n.webp",
      "miami_ugc/0085_ss_n.webp",
      "miami_ugc/0086_ss_n.webp",
      "miami_ugc/0087_ss_n.webp",
      "miami_ugc/0088_ss_n.webp",
      "miami_ugc/0089_ss_n.webp",
      "miami_ugc/0090_ss_n.webp",
      "miami_ugc/0091_ss_n.webp",
      "miami_ugc/0092_ss_n.webp",
      "miami_ugc/0093_ss_n.webp",
      "miami_ugc/0094_ss_n.webp",
      "miami_ugc/0095_ss_n.webp",
      "miami_ugc/0096_ss_n.webp",
      "miami_ugc/0097_ss_n.webp",
      "miami_ugc/0098_ss_n.webp",
      "miami_ugc/0099_ss_n.webp",
      "miami_ugc/0100_ss_n.webp",
      "miami_ugc/0101_ss_n.webp",
      "miami_ugc/0102_ss_n.webp",
      "miami_ugc/0103_ss_n.webp",
      "miami_ugc/0104_ss_n.webp",
      "miami_ugc/0105_ss_n.webp",
      "miami_ugc/0106_ss_n.webp",
      "miami_ugc/0107_ss_n.webp",
      "miami_ugc/0108_ss_n.webp",
      "miami_ugc/0109_ss_n.webp",
      "miami_ugc/0110_ss_n.webp",
      "miami_ugc/0111_ss_n.webp",
      "miami_ugc/0112_ss_n.webp",
      "miami_ugc/0113_ss_n.webp",
      "miami_ugc/0114_ss_n.webp",
      "miami_ugc/0115_ss_n.webp",
      "miami_ugc/0116_ss_n.webp",
      "miami_ugc/0117_ss_n.webp",
      "miami_ugc/0118_ss_n.webp",
      "miami_ugc/0119_ss_n.webp",
      "miami_ugc/0120_ss_n.webp"
    ]
  },
  "nyc_lifestyle": {
    "ac_f": [
      "nyc_lifestyle/0001_ac_f.webp",
      "nyc_lifestyle/0002_ac_f.webp",
      "nyc_lifestyle/0003_ac_f.webp",
      "nyc_lifestyle/0004_ac_f.webp",
      "nyc_lifestyle/0005_ac_f.webp",
      "nyc_lifestyle/0006_ac_f.webp",
      "nyc_lifestyle/0007_ac_f.webp",
      "nyc_lifestyle/0008_ac_f.webp",
      "nyc_lifestyle/0009_ac_f.webp",
      "nyc_lifestyle/0010_ac_f.webp",
      "nyc_lifestyle/0011_ac_f.webp",
      "nyc_lifestyle/0012_ac_f.webp",
      "nyc_lifestyle/0013_ac_f.webp",
      "nyc_lifestyle/0014_ac_f.webp",
      "nyc_lifestyle/0015_ac_f.webp",
      "nyc_lifestyle/0016_ac_f.webp",
      "nyc_lifestyle/0017_ac_f.webp",
      "nyc_lifestyle/0018_ac_f.webp"
    ],
    "as_f": [
      "nyc_lifestyle/0019_as_f.webp",
      "nyc_lifestyle/0020_as_f.webp",
      "nyc_lifestyle/0021_as_f.webp",
      "nyc_lifestyle/0022_as_f.webp",
      "nyc_lifestyle/0023_as_f.webp",
      "nyc_lifestyle/0024_as_f.webp",
      "nyc_lifestyle/0025_as_f.webp",
      "nyc_lifestyle/0026_as_f.webp",
      "nyc_lifestyle/0027_as_f.webp",
      "nyc_lifestyle/0028_as_f.webp",
      "nyc_lifestyle/0029_as_f.webp",
      "nyc_lifestyle/0030_as_f.webp",
      "nyc_lifestyle/0031_as_f.webp",
      "nyc_lifestyle/0032_as_f.webp",
      "nyc_lifestyle/0033_as_f.webp",
      "nyc_lifestyle/0035_as_f.webp",
      "nyc_lifestyle/0036_as_f.webp",
      "nyc_lifestyle/0037_as_f.webp",
      "nyc_lifestyle/0038_as_f.webp",
      "nyc_lifestyle/0039_as_f.webp",
      "nyc_lifestyle/0040_as_f.webp",
      "nyc_lifestyle/0094_as_f.webp",
      "nyc_lifestyle/0095_as_f.webp",
      "nyc_lifestyle/0096_as_f.webp",
      "nyc_lifestyle/0097_as_f.webp",
      "nyc_lifestyle/0098_as_f.webp",
      "nyc_lifestyle/0099_as_f.webp"
    ],
    "as_m": [
      "nyc_lifestyle/0041_as_m.webp",
      "nyc_lifestyle/0042_as_m.webp"
    ],
    "ps_n": [
      "nyc_lifestyle/0043_ps_n.webp",
      "nyc_lifestyle/0044_ps_n.webp",
      "nyc_lifestyle/0045_ps_n.webp",
      "nyc_lifestyle/0046_ps_n.webp",
      "nyc_lifestyle/0047_ps_n.webp",
      "nyc_lifestyle/0048_ps_n.webp",
      "nyc_lifestyle/0049_ps_n.webp",
      "nyc_lifestyle/0050_ps_n.webp",
      "nyc_lifestyle/0051_ps_n.webp",
      "nyc_lifestyle/0052_ps_n.webp",
      "nyc_lifestyle/0053_ps_n.webp",
      "nyc_lifestyle/0054_ps_n.webp",
      "nyc_lifestyle/0055_ps_n.webp",
      "nyc_lifestyle/0056_ps_n.webp",
      "nyc_lifestyle/0057_ps_n.webp",
      "nyc_lifestyle/0058_ps_n.webp",
      "nyc_lifestyle/0059_ps_n.webp",
      "nyc_lifestyle/0060_ps_n.webp",
      "nyc_lifestyle/0061_ps_n.webp",
      "nyc_lifestyle/0062_ps_n.webp",
      "nyc_lifestyle/0100_ps_n.webp",
      "nyc_lifestyle/0101_ps_n.webp",
      "nyc_lifestyle/0102_ps_n.webp",
      "nyc_lifestyle/0103_ps_n.webp"
    ],
    "ss_n": [
      "nyc_lifestyle/0063_ss_n.webp",
      "nyc_lifestyle/0064_ss_n.webp",
      "nyc_lifestyle/0065_ss_n.webp",
      "nyc_lifestyle/0066_ss_n.webp",
      "nyc_lifestyle/0067_ss_n.webp",
      "nyc_lifestyle/0068_ss_n.webp",
      "nyc_lifestyle/0069_ss_n.webp",
      "nyc_lifestyle/0070_ss_n.webp",
      "nyc_lifestyle/0071_ss_n.webp",
      "nyc_lifestyle/0072_ss_n.webp",
      "nyc_lifestyle/0073_ss_n.webp",
      "nyc_lifestyle/0074_ss_n.webp",
      "nyc_lifestyle/0075_ss_n.webp",
      "nyc_lifestyle/0076_ss_n.webp",
      "nyc_lifestyle/0077_ss_n.webp",
      "nyc_lifestyle/0078_ss_n.webp",
      "nyc_lifestyle/0079_ss_n.webp",
      "nyc_lifestyle/0080_ss_n.webp",
      "nyc_lifestyle/0081_ss_n.webp",
      "nyc_lifestyle/0082_ss_n.webp",
      "nyc_lifestyle/0083_ss_n.webp",
      "nyc_lifestyle/0084_ss_n.webp",
      "nyc_lifestyle/0085_ss_n.webp",
      "nyc_lifestyle/0086_ss_n.webp",
      "nyc_lifestyle/0087_ss_n.webp",
      "nyc_lifestyle/0088_ss_n.webp",
      "nyc_lifestyle/0089_ss_n.webp",
      "nyc_lifestyle/0090_ss_n.webp",
      "nyc_lifestyle/0091_ss_n.webp",
      "nyc_lifestyle/0092_ss_n.webp",
      "nyc_lifestyle/0093_ss_n.webp",
      "nyc_lifestyle/0104_ss_n.webp",
      "nyc_lifestyle/0105_ss_n.webp",
      "nyc_lifestyle/0106_ss_n.webp",
      "nyc_lifestyle/0107_ss_n.webp",
      "nyc_lifestyle/0108_ss_n.webp",
      "nyc_lifestyle/0109_ss_n.webp",
      "nyc_lifestyle/0110_ss_n.webp",
      "nyc_lifestyle/0111_ss_n.webp",
      "nyc_lifestyle/0112_ss_n.webp",
      "nyc_lifestyle/0113_ss_n.webp",
      "nyc_lifestyle/0114_ss_n.webp",
      "nyc_lifestyle/0115_ss_n.webp",
      "nyc_lifestyle/0116_ss_n.webp",
      "nyc_lifestyle/0117_ss_n.webp",
      "nyc_lifestyle/0118_ss_n.webp",
      "nyc_lifestyle/0119_ss_n.webp",
      "nyc_lifestyle/0120_ss_n.webp"
    ]
  },
  "private_school_lifestyle": {
    "ac_f": [
      "private_school_lifestyle/0001_ac_f.webp",
      "private_school_lifestyle/0002_ac_f.webp",
      "private_school_lifestyle/0004_ac_f.webp",
      "private_school_lifestyle/0006_ac_f.webp",
      "private_school_lifestyle/0007_ac_f.webp",
      "private_school_lifestyle/0009_ac_f.webp",
      "private_school_lifestyle/0011_ac_f.webp",
      "private_school_lifestyle/0012_ac_f.webp",
      "private_school_lifestyle/0014_ac_f.webp",
      "private_school_lifestyle/0016_ac_f.webp",
      "private_school_lifestyle/0017_ac_f.webp"
    ],
    "ac_m": [
      "private_school_lifestyle/0003_ac_m.webp",
      "private_school_lifestyle/0005_ac_m.webp",
      "private_school_lifestyle/0008_ac_m.webp",
      "private_school_lifestyle/0010_ac_m.webp",
      "private_school_lifestyle/0013_ac_m.webp",
      "private_school_lifestyle/0015_ac_m.webp",
      "private_school_lifestyle/0018_ac_m.webp"
    ],
    "as_f": [
      "private_school_lifestyle/0019_as_f.webp",
      "private_school_lifestyle/0021_as_f.webp",
      "private_school_lifestyle/0023_as_f.webp",
      "private_school_lifestyle/0025_as_f.webp",
      "private_school_lifestyle/0026_as_f.webp",
      "private_school_lifestyle/0028_as_f.webp",
      "private_school_lifestyle/0030_as_f.webp",
      "private_school_lifestyle/0031_as_f.webp",
      "private_school_lifestyle/0033_as_f.webp",
      "private_school_lifestyle/0035_as_f.webp",
      "private_school_lifestyle/0037_as_f.webp",
      "private_school_lifestyle/0039_as_f.webp",
      "private_school_lifestyle/0041_as_f.webp",
      "private_school_lifestyle/0043_as_f.webp",
      "private_school_lifestyle/0045_as_f.webp",
      "private_school_lifestyle/0047_as_f.webp"
    ],
    "as_m": [
      "private_school_lifestyle/0020_as_m.webp",
      "private_school_lifestyle/0022_as_m.webp",
      "private_school_lifestyle/0024_as_m.webp",
      "private_school_lifestyle/0027_as_m.webp",
      "private_school_lifestyle/0029_as_m.webp",
      "private_school_lifestyle/0032_as_m.webp",
      "private_school_lifestyle/0034_as_m.webp",
      "private_school_lifestyle/0036_as_m.webp",
      "private_school_lifestyle/0038_as_m.webp",
      "private_school_lifestyle/0040_as_m.webp",
      "private_school_lifestyle/0042_as_m.webp",
      "private_school_lifestyle/0044_as_m.webp",
      "private_school_lifestyle/0048_as_m.webp"
    ],
    "ps_f": [
      "private_school_lifestyle/0049_ps_f.webp",
      "private_school_lifestyle/0051_ps_f.webp",
      "private_school_lifestyle/0053_ps_f.webp",
      "private_school_lifestyle/0054_ps_f.webp",
      "private_school_lifestyle/0056_ps_f.webp",
      "private_school_lifestyle/0057_ps_f.webp",
      "private_school_lifestyle/0059_ps_f.webp",
      "private_school_lifestyle/0061_ps_f.webp",
      "private_school_lifestyle/0063_ps_f.webp",
      "private_school_lifestyle/0065_ps_f.webp",
      "private_school_lifestyle/0067_ps_f.webp",
      "private_school_lifestyle/0069_ps_f.webp",
      "private_school_lifestyle/0070_ps_f.webp",
      "private_school_lifestyle/0072_ps_f.webp"
    ],
    "ps_m": [
      "private_school_lifestyle/0050_ps_m.webp",
      "private_school_lifestyle/0052_ps_m.webp",
      "private_school_lifestyle/0055_ps_m.webp",
      "private_school_lifestyle/0058_ps_m.webp",
      "private_school_lifestyle/0060_ps_m.webp",
      "private_school_lifestyle/0062_ps_m.webp",
      "private_school_lifestyle/0064_ps_m.webp",
      "private_school_lifestyle/0066_ps_m.webp",
      "private_school_lifestyle/0068_ps_m.webp",
      "private_school_lifestyle/0071_ps_m.webp"
    ],
    "ss_n": [
      "private_school_lifestyle/0073_ss_n.webp",
      "private_school_lifestyle/0074_ss_n.webp",
      "private_school_lifestyle/0075_ss_n.webp",
      "private_school_lifestyle/0076_ss_n.webp",
      "private_school_lifestyle/0077_ss_n.webp",
      "private_school_lifestyle/0078_ss_n.webp",
      "private_school_lifestyle/0079_ss_n.webp",
      "private_school_lifestyle/0080_ss_n.webp",
      "private_school_lifestyle/0081_ss_n.webp",
      "private_school_lifestyle/0082_ss_n.webp",
      "private_school_lifestyle/0083_ss_n.webp",
      "private_school_lifestyle/0084_ss_n.webp",
      "private_school_lifestyle/0085_ss_n.webp",
      "private_school_lifestyle/0086_ss_n.webp",
      "private_school_lifestyle/0087_ss_n.webp",
      "private_school_lifestyle/0088_ss_n.webp",
      "private_school_lifestyle/0089_ss_n.webp",
      "private_school_lifestyle/0090_ss_n.webp",
      "private_school_lifestyle/0091_ss_n.webp",
      "private_school_lifestyle/0092_ss_n.webp",
      "private_school_lifestyle/0093_ss_n.webp",
      "private_school_lifestyle/0094_ss_n.webp",
      "private_school_lifestyle/0095_ss_n.webp",
      "private_school_lifestyle/0096_ss_n.webp",
      "private_school_lifestyle/0097_ss_n.webp",
      "private_school_lifestyle/0098_ss_n.webp",
      "private_school_lifestyle/0099_ss_n.webp",
      "private_school_lifestyle/0100_ss_n.webp",
      "private_school_lifestyle/0101_ss_n.webp",
      "private_school_lifestyle/0102_ss_n.webp",
      "private_school_lifestyle/0103_ss_n.webp",
      "private_school_lifestyle/0104_ss_n.webp",
      "private_school_lifestyle/0105_ss_n.webp",
      "private_school_lifestyle/0106_ss_n.webp",
      "private_school_lifestyle/0107_ss_n.webp",
      "private_school_lifestyle/0108_ss_n.webp",
      "private_school_lifestyle/0109_ss_n.webp",
      "private_school_lifestyle/0110_ss_n.webp",
      "private_school_lifestyle/0111_ss_n.webp",
      "private_school_lifestyle/0112_ss_n.webp",
      "private_school_lifestyle/0113_ss_n.webp",
      "private_school_lifestyle/0114_ss_n.webp",
      "private_school_lifestyle/0115_ss_n.webp",
      "private_school_lifestyle/0116_ss_n.webp",
      "private_school_lifestyle/0117_ss_n.webp",
      "private_school_lifestyle/0118_ss_n.webp",
      "private_school_lifestyle/0119_ss_n.webp",
      "private_school_lifestyle/0120_ss_n.webp"
    ]
  },
  "soft-luxury-lifestyle": {
    "ac_f": [
      "soft-luxury-lifestyle/0001_ac_f.webp",
      "soft-luxury-lifestyle/0002_ac_f.webp",
      "soft-luxury-lifestyle/0004_ac_f.webp",
      "soft-luxury-lifestyle/0006_ac_f.webp",
      "soft-luxury-lifestyle/0008_ac_f.webp",
      "soft-luxury-lifestyle/0009_ac_f.webp",
      "soft-luxury-lifestyle/0011_ac_f.webp",
      "soft-luxury-lifestyle/0013_ac_f.webp",
      "soft-luxury-lifestyle/0015_ac_f.webp",
      "soft-luxury-lifestyle/0017_ac_f.webp"
    ],
    "ac_m": [
      "soft-luxury-lifestyle/0003_ac_m.webp",
      "soft-luxury-lifestyle/0005_ac_m.webp",
      "soft-luxury-lifestyle/0007_ac_m.webp",
      "soft-luxury-lifestyle/0010_ac_m.webp",
      "soft-luxury-lifestyle/0012_ac_m.webp",
      "soft-luxury-lifestyle/0014_ac_m.webp",
      "soft-luxury-lifestyle/0016_ac_m.webp",
      "soft-luxury-lifestyle/0018_ac_m.webp"
    ],
    "as_f": [
      "soft-luxury-lifestyle/0019_as_f.webp",
      "soft-luxury-lifestyle/0021_as_f.webp",
      "soft-luxury-lifestyle/0023_as_f.webp",
      "soft-luxury-lifestyle/0025_as_f.webp",
      "soft-luxury-lifestyle/0027_as_f.webp",
      "soft-luxury-lifestyle/0029_as_f.webp",
      "soft-luxury-lifestyle/0031_as_f.webp",
      "soft-luxury-lifestyle/0033_as_f.webp",
      "soft-luxury-lifestyle/0035_as_f.webp",
      "soft-luxury-lifestyle/0037_as_f.webp",
      "soft-luxury-lifestyle/0039_as_f.webp",
      "soft-luxury-lifestyle/0041_as_f.webp",
      "soft-luxury-lifestyle/0043_as_f.webp",
      "soft-luxury-lifestyle/0045_as_f.webp",
      "soft-luxury-lifestyle/0047_as_f.webp",
      "soft-luxury-lifestyle/0049_as_f.webp"
    ],
    "as_m": [
      "soft-luxury-lifestyle/0020_as_m.webp",
      "soft-luxury-lifestyle/0022_as_m.webp",
      "soft-luxury-lifestyle/0024_as_m.webp",
      "soft-luxury-lifestyle/0026_as_m.webp",
      "soft-luxury-lifestyle/0028_as_m.webp",
      "soft-luxury-lifestyle/0030_as_m.webp",
      "soft-luxury-lifestyle/0032_as_m.webp",
      "soft-luxury-lifestyle/0034_as_m.webp",
      "soft-luxury-lifestyle/0036_as_m.webp",
      "soft-luxury-lifestyle/0038_as_m.webp",
      "soft-luxury-lifestyle/0040_as_m.webp",
      "soft-luxury-lifestyle/0042_as_m.webp",
      "soft-luxury-lifestyle/0044_as_m.webp",
      "soft-luxury-lifestyle/0046_as_m.webp",
      "soft-luxury-lifestyle/0048_as_m.webp"
    ],
    "ps_f": [
      "soft-luxury-lifestyle/0050_ps_f.webp",
      "soft-luxury-lifestyle/0052_ps_f.webp",
      "soft-luxury-lifestyle/0054_ps_f.webp",
      "soft-luxury-lifestyle/0056_ps_f.webp",
      "soft-luxury-lifestyle/0058_ps_f.webp",
      "soft-luxury-lifestyle/0060_ps_f.webp",
      "soft-luxury-lifestyle/0062_ps_f.webp",
      "soft-luxury-lifestyle/0064_ps_f.webp",
      "soft-luxury-lifestyle/0066_ps_f.webp",
      "soft-luxury-lifestyle/0068_ps_f.webp",
      "soft-luxury-lifestyle/0072_ps_f.webp"
    ],
    "ps_m": [
      "soft-luxury-lifestyle/0051_ps_m.webp",
      "soft-luxury-lifestyle/0053_ps_m.webp",
      "soft-luxury-lifestyle/0055_ps_m.webp",
      "soft-luxury-lifestyle/0057_ps_m.webp",
      "soft-luxury-lifestyle/0059_ps_m.webp",
      "soft-luxury-lifestyle/0061_ps_m.webp",
      "soft-luxury-lifestyle/0063_ps_m.webp",
      "soft-luxury-lifestyle/0065_ps_m.webp",
      "soft-luxury-lifestyle/0067_ps_m.webp",
      "soft-luxury-lifestyle/0069_ps_m.webp",
      "soft-luxury-lifestyle/0071_ps_m.webp",
      "soft-luxury-lifestyle/0073_ps_m.webp"
    ],
    "ss_n": [
      "soft-luxury-lifestyle/0074_ss_n.webp",
      "soft-luxury-lifestyle/0075_ss_n.webp",
      "soft-luxury-lifestyle/0076_ss_n.webp",
      "soft-luxury-lifestyle/0077_ss_n.webp",
      "soft-luxury-lifestyle/0078_ss_n.webp",
      "soft-luxury-lifestyle/0079_ss_n.webp",
      "soft-luxury-lifestyle/0080_ss_n.webp",
      "soft-luxury-lifestyle/0081_ss_n.webp",
      "soft-luxury-lifestyle/0082_ss_n.webp",
      "soft-luxury-lifestyle/0083_ss_n.webp",
      "soft-luxury-lifestyle/0084_ss_n.webp",
      "soft-luxury-lifestyle/0085_ss_n.webp",
      "soft-luxury-lifestyle/0086_ss_n.webp",
      "soft-luxury-lifestyle/0087_ss_n.webp",
      "soft-luxury-lifestyle/0088_ss_n.webp",
      "soft-luxury-lifestyle/0089_ss_n.webp",
      "soft-luxury-lifestyle/0090_ss_n.webp",
      "soft-luxury-lifestyle/0091_ss_n.webp",
      "soft-luxury-lifestyle/0092_ss_n.webp",
      "soft-luxury-lifestyle/0093_ss_n.webp",
      "soft-luxury-lifestyle/0094_ss_n.webp",
      "soft-luxury-lifestyle/0095_ss_n.webp",
      "soft-luxury-lifestyle/0096_ss_n.webp",
      "soft-luxury-lifestyle/0097_ss_n.webp",
      "soft-luxury-lifestyle/0098_ss_n.webp",
      "soft-luxury-lifestyle/0099_ss_n.webp",
      "soft-luxury-lifestyle/0100_ss_n.webp",
      "soft-luxury-lifestyle/0101_ss_n.webp",
      "soft-luxury-lifestyle/0102_ss_n.webp",
      "soft-luxury-lifestyle/0103_ss_n.webp",
      "soft-luxury-lifestyle/0104_ss_n.webp",
      "soft-luxury-lifestyle/0105_ss_n.webp",
      "soft-luxury-lifestyle/0106_ss_n.webp",
      "soft-luxury-lifestyle/0107_ss_n.webp",
      "soft-luxury-lifestyle/0108_ss_n.webp",
      "soft-luxury-lifestyle/0109_ss_n.webp",
      "soft-luxury-lifestyle/0110_ss_n.webp",
      "soft-luxury-lifestyle/0111_ss_n.webp",
      "soft-luxury-lifestyle/0112_ss_n.webp",
      "soft-luxury-lifestyle/0113_ss_n.webp",
      "soft-luxury-lifestyle/0115_ss_n.webp",
      "soft-luxury-lifestyle/0116_ss_n.webp",
      "soft-luxury-lifestyle/0117_ss_n.webp",
      "soft-luxury-lifestyle/0118_ss_n.webp",
      "soft-luxury-lifestyle/0119_ss_n.webp",
      "soft-luxury-lifestyle/0120_ss_n.webp"
    ]
  },
}

shottypes = [
  "ac", "as", "ps", "ss"
]

gender = {
  "ac": ["m", "f"],
  "as": ["m", "f"],
  "ps": ["m", "f"],
  "ss": "n"
}
def getStockImage(stock_pack_id: str, shot_type: str | None = None, gender_char: str | None = None, index: int | None = None):
  """
  Get a random stock image from the manifest.
  
  Args:
    stock_pack_id: ID of the stock pack
    shot_type: Shot type (ac, as, ps, ss) - random if None
    gender_char: Gender character (m, f, n) - random if None
    index: Specific index in the list (optional)
  
  Returns:
    Random image path from the manifest
  """
  # Determine shot type
  if not shot_type:
    shot_type = shottypes[random.randint(0, len(shottypes) - 1)]
  
  # Determine gender character
  if not gender_char:
    gender_list = gender[shot_type]
    if isinstance(gender_list, list):
      gender_char = gender_list[random.randint(0, len(gender_list) - 1)]
    else:
      gender_char = gender_list
  
  prefix = f"{shot_type}_{gender_char}"
  
  # Validate prefix exists
  if prefix not in stock_pack_manifest[stock_pack_id]:
    raise ValueError(f"Incorrect stock image selection: pack={stock_pack_id}, prefix={prefix}")
  
  imgs = stock_pack_manifest[stock_pack_id][prefix]
  
  # Return specific index or random
  if index is not None:
    return imgs[index]
  return "https://stock-read-worker.useradius.workers.dev/file?key=" + imgs[random.randint(0, len(imgs) - 1)]