stock_packs = [
    {
        "idx": 0,
        "id": 1,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "clean girl lifestyle",
        "description": "Minimal, soft, wellness-focused visuals featuring tidy spaces, natural light, and effortless beauty aesthetics.",
        "image_count": None,
        "bucket_directory": "clean_girl_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 1,
        "id": 2,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "coquette lifestyle",
        "description": "Romantic, feminine visuals inspired by bows, lace, soft pastels, and dreamy vintage-girly energy.",
        "image_count": None,
        "bucket_directory": "coquette_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 2,
        "id": 3,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "cottage core lifestyle",
        "description": "Nature-inspired cozy visuals with rustic textures, soft countryside charm, and slow-living energy.",
        "image_count": None,
        "bucket_directory": "cottege-core-lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 3,
        "id": 4,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "dark luxury lifestyle",
        "description": "High-contrast, moody luxury visuals with deep tones, premium textures, and elevated editorial energy.",
        "image_count": None,
        "bucket_directory": "dark_luxury_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 4,
        "id": 5,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "miami lifestyle",
        "description": "Vibrant, sun-soaked visuals with tropical colors, nightlife energy, and bold coastal luxury.",
        "image_count": None,
        "bucket_directory": "miami_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 5,
        "id": 6,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "nyc lifestyle",
        "description": "Urban, fast-paced visuals capturing city grit, modern fashion, architecture, and everyday New York energy.",
        "image_count": None,
        "bucket_directory": "nyc_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 6,
        "id": 7,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "private school lifestyle",
        "description": "Preppy, polished visuals featuring uniforms, structured outfits, academic settings, and elite-campus energy.",
        "image_count": None,
        "bucket_directory": "private_school_lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
    {
        "idx": 7,
        "id": 8,
        "created_at": "2026-03-19 00:39:34.541129+00",
        "name": "soft luxury lifestyle",
        "description": "Light-toned premium visuals with airy textures, neutrals, and understated high-end elegance.",
        "image_count": None,
        "bucket_directory": "soft-luxury-lifestyle",
        "tags": None,
        "thumbnail_urls": None,
    },
]

stock_pack_dirs = [pack["name"] for pack in stock_packs]