export const SLIDE_LAYOUTS = {
  hook: {
    // id: "S1",
    name: "hook",
    // background: {
    //   type: "image",
    //   color: "#e3e3e3",
    // },
    // dynamic: true,
    // template_id: "",
    // created_at: "2026-01-06T21:52:18.745Z",
    text_elements: [
      {
        id: "text-1767736354031",
        type: "text",
        content: "Hook text here",
        font_size: 48,
        font_family: "Proxima Nova, Inter, Arial",
        font_style: "bold",
        color: "#ffffff",
        x: 100,
        y: 600,
        width: 880,
        align: "center",
        stroke: "#000000",
        stroke_width: 4,
        shadow_color: "#000000",
        shadow_blur: 6,
        shadow_offset_x: 0,
        shadow_offset_y: 2,
        shadow_opacity: 0.5,
        line_height: 1.3,
      },
    ],
  },
  header_and_body: {
    // id: "S1",
    name: "header_and_body",
    // background: {
    //   type: "image",
    //   color: "#e3e3e3",
    // },
    // dynamic: true,
    // template_id: "",
    // created_at: "2026-01-06T21:52:18.745Z",
    text_elements: [
      {
        id: "text-1767736354031",
        type: "text",
        content: "Header text here",
        font_size: 55,
        font_family: "Proxima Nova, Inter, Arial",
        font_style: "bold",
        color: "#ffffff",
        x: 100,
        y: 190,
        width: 880,
        align: "center",
        stroke: "#000000",
        stroke_width: 4,
        shadow_color: "#000000",
        shadow_blur: 6,
        shadow_offset_x: 0,
        shadow_offset_y: 2,
        shadow_opacity: 0.5,
        line_height: 1.3,
      },
      {
        id: "text-1767738943620",
        type: "text",
        content: "Body text here",
        font_size: 48,
        font_family: "Inter",
        font_style: "normal",
        color: "#ffffff",
        x: 100,
        y: 500,
        width: 880,
        align: "center",
      },
    ],
  },
  header: {
    // id: "S1",
    name: "header",
    // background: {
    //   type: "image",
    //   color: "#e3e3e3",
    // },
    // dynamic: true,
    // template_id: "",
    // created_at: "2026-01-06T21:52:18.745Z",
    text_elements: [
      {
        id: "text-1767736354031",
        type: "text",
        content: "Header text here",
        font_size: 55,
        font_family: "Proxima Nova, Inter, Arial",
        font_style: "bold",
        color: "#ffffff",
        x: 100,
        y: 190,
        width: 880,
        align: "center",
        stroke: "#000000",
        stroke_width: 4,
        shadow_color: "#000000",
        shadow_blur: 6,
        shadow_offset_x: 0,
        shadow_offset_y: 2,
        shadow_opacity: 0.5,
        line_height: 1.3,
      },
    ],
  },
  body: {
    // id: "S1",
    name: "body",
    // background: {
    //   type: "image",
    //   color: "#e3e3e3",
    // },
    // dynamic: true,
    // template_id: "",
    // created_at: "2026-01-06T21:52:18.745Z",
    text_elements: [
      {
        id: "text-1767738943620",
        type: "text",
        content: "Body text here",
        font_size: 48,
        font_family: "Inter",
        font_style: "normal",
        color: "#ffffff",
        x: 100,
        y: 500,
        width: 880,
        align: "center",
      },
    ],
  },
};
